version: '3.7'
services:
  nginx:
    image: kokt0203/nginx-geoip:latest
    container_name: UdonMeet-Auth-Proxy
    ports:
      - 4100:4100
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
  AuthServer-1:
    image: 'kokt0203/udonmeet:latest'
    container_name: UdonMeet-Authentication-Express-server-1
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    ports:
      - ${PORT}
    restart: always
  AuthServer-2:
    image: 'kokt0203/udonmeet:latest'
    container_name: UdonMeet-Authentication-Express-server-2
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    ports:
      - ${PORT}
    restart: always
