version: '3.7'
services:
  nginx:
    image: nginx:1.21.6-alpine
    container_name: Pumassi-Proxy
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
  AuthServer-1:
    image: 'kokt0203/pumassi:latest'
    container_name: UdonMeet-Authentication-Express-server
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    volumes:
      - ~/Document/code/DSM/Backend-Pumassi/logs/:/app/dist/logs # 연결할 로컬 디렉토리
    ports:
      - ${PORT}
    restart: always
